-- Lightweight authenticated portfolio guestbook.
-- Public visitors can read active comments; only authenticated users can post.
-- Comment identity is derived server-side from Supabase Auth, not trusted from the browser.

create extension if not exists pg_cron;

create table if not exists public.portfolio_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null check (char_length(author_name) between 1 and 80),
  avatar_url text check (avatar_url is null or char_length(avatar_url) <= 2048),
  body text not null check (char_length(body) between 1 and 150),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '6 months')
);

create index if not exists portfolio_comments_created_at_idx
  on public.portfolio_comments (created_at desc);

create index if not exists portfolio_comments_expires_at_idx
  on public.portfolio_comments (expires_at);

create index if not exists portfolio_comments_user_created_idx
  on public.portfolio_comments (user_id, created_at desc);

alter table public.portfolio_comments enable row level security;

revoke all on table public.portfolio_comments from anon, authenticated;
grant select on table public.portfolio_comments to anon, authenticated;

drop policy if exists "Public can read active portfolio comments" on public.portfolio_comments;
create policy "Public can read active portfolio comments"
  on public.portfolio_comments
  for select
  to anon, authenticated
  using (expires_at > now());

create or replace function public.add_portfolio_comment(comment_text text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_body text := btrim(comment_text);
  v_author_name text;
  v_avatar_url text;
  v_comment_id bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if v_body is null or char_length(v_body) = 0 then
    raise exception 'Comment cannot be empty';
  end if;

  if char_length(v_body) > 150 then
    raise exception 'Comment exceeds 150 characters';
  end if;

  if exists (
    select 1
    from public.portfolio_comments
    where user_id = v_user_id
      and created_at > now() - interval '30 seconds'
  ) then
    raise exception 'Please wait before posting another comment';
  end if;

  select
    left(
      coalesce(
        nullif(btrim(raw_user_meta_data ->> 'full_name'), ''),
        nullif(btrim(raw_user_meta_data ->> 'name'), ''),
        'Google user'
      ),
      80
    ),
    nullif(
      left(
        coalesce(
          nullif(btrim(raw_user_meta_data ->> 'avatar_url'), ''),
          nullif(btrim(raw_user_meta_data ->> 'picture'), ''),
          ''
        ),
        2048
      ),
      ''
    )
  into v_author_name, v_avatar_url
  from auth.users
  where id = v_user_id
    and raw_app_meta_data ->> 'provider' = 'google';

  if v_author_name is null then
    raise exception 'Authenticated user record not found';
  end if;

  insert into public.portfolio_comments (
    user_id,
    author_name,
    avatar_url,
    body,
    expires_at
  )
  values (
    v_user_id,
    v_author_name,
    v_avatar_url,
    v_body,
    now() + interval '6 months'
  )
  returning id into v_comment_id;

  return v_comment_id;
end;
$$;

revoke all on function public.add_portfolio_comment(text) from public;
grant execute on function public.add_portfolio_comment(text) to authenticated;

-- Keep exactly one tiny daily retention job even if this migration is re-applied manually.
do $$
declare
  v_job_id bigint;
begin
  for v_job_id in
    select jobid
    from cron.job
    where jobname = 'portfolio-comments-retention'
  loop
    perform cron.unschedule(v_job_id);
  end loop;
end
$$;

select cron.schedule(
  'portfolio-comments-retention',
  '17 3 * * *',
  $$delete from public.portfolio_comments where expires_at <= now()$$
);
